import { revalidatePath } from "next/cache";
import { UsersRound } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { ensureDefaultAccessProfiles } from "@/modules/auth/server/rbac";
import { requireServerRole } from "@/modules/auth/server/session";

type Profile={id:string;name:string;master:boolean};
type UserRow={id:string;name:string;email:string;role:string;profileId:string|null;profileName:string|null};

async function assignProfile(formData:FormData){"use server";const actor=await requireServerRole(["OWNER","ADMIN"]);if(!actor)throw new Error("Autenticação necessária.");const userId=String(formData.get("userId")??"");const profileId=String(formData.get("profileId")??"");const valid=await prisma.$queryRawUnsafe<{id:string}[]>(`SELECT p."id" FROM "AccessProfile" p JOIN "User" u ON u."companyId"=p."companyId" WHERE p."id"=$1 AND u."id"=$2 AND u."companyId"=$3 LIMIT 1`,profileId,userId,actor.companyId);if(!valid[0])throw new Error("Usuário ou perfil inválido.");await prisma.$executeRawUnsafe(`INSERT INTO "UserAccessProfile" ("userId","profileId") VALUES ($1,$2) ON CONFLICT ("userId") DO UPDATE SET "profileId"=$2`,userId,profileId);revalidatePath("/rh/configuracoes/acessos");}

export default async function UserAccessPage(){const actor=await requireServerRole(["OWNER","ADMIN"]);if(!actor)return <main className="p-8">Autenticação necessária.</main>;await ensureDefaultAccessProfiles(actor.companyId);const profiles=await prisma.$queryRawUnsafe<Profile[]>(`SELECT "id","name","master" FROM "AccessProfile" WHERE "companyId"=$1 AND "active"=true ORDER BY "master" DESC,"name"`,actor.companyId);const users=await prisma.$queryRawUnsafe<UserRow[]>(`SELECT u."id",u."name",u."email",u."role",x."profileId",p."name" AS "profileName" FROM "User" u LEFT JOIN "UserAccessProfile" x ON x."userId"=u."id" LEFT JOIN "AccessProfile" p ON p."id"=x."profileId" WHERE u."companyId"=$1 AND u."active"=true ORDER BY u."name"`,actor.companyId);return <main className="px-4 py-6 md:px-7 md:py-8"><div className="mx-auto max-w-5xl"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#eaf3fb] text-[#154b7a]"><UsersRound/></div><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#154b7a]">Segurança · Usuários</p><h1 className="text-3xl font-bold text-[#0b2947]">Acessos dos profissionais</h1><p className="mt-1 text-sm text-slate-500">Atribua a cada profissional um perfil. OWNER/ADMIN continuam com privilégio master por segurança.</p></div></div><section className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="divide-y divide-slate-100">{users.map(user=><form key={user.id} action={assignProfile} className="grid gap-3 p-5 md:grid-cols-[1fr_220px_110px] md:items-center"><input type="hidden" name="userId" value={user.id}/><div><p className="font-semibold text-slate-800">{user.name}</p><p className="text-xs text-slate-500">{user.email} · papel técnico {user.role}</p></div><select name="profileId" defaultValue={user.profileId??""} required className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Selecione o perfil</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}{p.master?" · MASTER":""}</option>)}</select><button className="h-10 rounded-xl bg-[#0b2947] text-xs font-semibold text-white">Aplicar</button></form>)}</div></section></div></main>}
