import { revalidatePath } from "next/cache";
import { FileHeart, Plus } from "lucide-react";

import { prisma } from "@/lib/prisma";

function text(formData: FormData, key: string) { const value = formData.get(key); return typeof value === "string" && value.trim() ? value.trim() : null; }
function date(formData: FormData, key: string) { const value = text(formData, key); return value ? new Date(`${value}T12:00:00`) : null; }
async function createLeave(formData: FormData) {
  "use server";
  const company = await prisma.company.findFirst({ where: { active: true }, select: { id: true } });
  if (!company) throw new Error("Empresa ativa não encontrada.");
  const employeeId = text(formData, "employeeId"); const type = text(formData, "type"); const startDate = date(formData, "startDate");
  if (!employeeId || !type || !startDate) throw new Error("Colaborador, tipo e início são obrigatórios.");
  await prisma.hrLeaveRequest.create({ data: { companyId: company.id, employeeId, type, startDate, endDate: date(formData, "endDate"), cid: text(formData, "cid"), benefitNumber: text(formData, "benefitNumber"), notes: text(formData, "notes") } });
  revalidatePath("/dp/afastamentos"); revalidatePath("/pessoas");
}
export default async function LeavesPage() {
  const company = await prisma.company.findFirst({ where: { active: true }, select: { id: true } }); const companyId = company?.id;
  const [employees, leaves] = companyId ? await Promise.all([
    prisma.hrEmployee.findMany({ where: { companyId, active: true }, orderBy: { fullName: "asc" }, select: { id: true, fullName: true } }),
    prisma.hrLeaveRequest.findMany({ where: { companyId }, orderBy: { createdAt: "desc" }, take: 50, include: { employee: { select: { fullName: true } } } }),
  ]) : [[], []];
  const today = new Date(); const active = leaves.filter((item)=>item.startDate<=today && (!item.endDate || item.endDate>=today)).length;
  return <main className="px-4 py-6 md:px-7 md:py-8"><div className="mx-auto max-w-[1360px]"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#154b7a]">DP · Afastamentos</p><h1 className="mt-2 text-3xl font-bold text-[#0b2947]">Afastamentos</h1><p className="mt-2 text-sm text-slate-600">Atestados, licenças, previdenciário, retorno e histórico funcional.</p></div>
  <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Afastamentos ativos",active],["Registros",leaves.length],["Colaboradores",employees.length],["Pendentes",leaves.filter((i)=>i.status==="PENDING").length]].map(([l,v])=><article key={String(l)} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs text-slate-500">{l}</p><strong className="mt-2 block text-2xl text-[#0b2947]">{String(v)}</strong></article>)}</section>
  <section className="mt-5 grid gap-5 xl:grid-cols-[420px_1fr]"><form action={createLeave} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#eaf3fb] text-[#154b7a]"><Plus className="h-5 w-5"/></div><div><h2 className="font-bold text-[#0b2947]">Registrar afastamento</h2><p className="text-xs text-slate-500">Gera histórico no dossiê.</p></div></div><div className="mt-5 space-y-4"><select name="employeeId" required className="h-11 w-full rounded-2xl border border-slate-200 px-3 text-sm"><option value="">Selecione o colaborador</option>{employees.map(i=><option key={i.id} value={i.id}>{i.fullName}</option>)}</select><select name="type" required className="h-11 w-full rounded-2xl border border-slate-200 px-3 text-sm"><option value="">Tipo</option><option>Atestado médico</option><option>Auxílio-doença</option><option>Acidente de trabalho</option><option>Licença maternidade</option><option>Licença paternidade</option><option>Licença não remunerada</option><option>Outro</option></select><div className="grid grid-cols-2 gap-3"><input name="startDate" type="date" required className="h-11 rounded-2xl border border-slate-200 px-3 text-sm"/><input name="endDate" type="date" className="h-11 rounded-2xl border border-slate-200 px-3 text-sm"/></div><div className="grid grid-cols-2 gap-3"><input name="cid" placeholder="CID (quando aplicável)" className="h-11 rounded-2xl border border-slate-200 px-3 text-sm"/><input name="benefitNumber" placeholder="Benefício INSS" className="h-11 rounded-2xl border border-slate-200 px-3 text-sm"/></div><textarea name="notes" rows={3} placeholder="Observações" className="w-full rounded-2xl border border-slate-200 p-4 text-sm"/><button className="h-11 w-full rounded-2xl bg-[#0b2947] text-sm font-semibold text-white">Salvar afastamento</button></div></form>
  <article className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-6"><FileHeart className="h-5 w-5 text-[#154b7a]"/><div><h2 className="font-bold text-[#0b2947]">Histórico de afastamentos</h2><p className="text-xs text-slate-500">Registros mais recentes.</p></div></div>{leaves.length===0?<div className="p-12 text-center text-sm text-slate-500">Nenhum afastamento registrado.</div>:<div className="divide-y divide-slate-100">{leaves.map(item=><div key={item.id} className="grid gap-2 p-5 md:grid-cols-[1.3fr_1fr_1fr_120px] md:items-center"><div><p className="font-semibold text-slate-800">{item.employee.fullName}</p><p className="text-xs text-slate-400">{item.type}</p></div><span className="text-sm text-slate-600">{new Intl.DateTimeFormat("pt-BR").format(item.startDate)}</span><span className="text-sm text-slate-600">{item.endDate?new Intl.DateTimeFormat("pt-BR").format(item.endDate):"Em aberto"}</span><span className="w-fit rounded-full bg-amber-50 px-2.5 py-1 text-[11px] font-semibold text-amber-700">{item.status}</span></div>)}</div>}</article></section>
  </div></main>;
}
