import { revalidatePath } from "next/cache";
import { MessageSquareText, Plus, ShieldCheck } from "lucide-react";

import { prisma } from "@/lib/prisma";

function text(formData: FormData, key: string) { const value=formData.get(key); return typeof value==="string"&&value.trim()?value.trim():null; }
async function createTicket(formData: FormData){
  "use server";
  const company=await prisma.company.findFirst({where:{active:true},select:{id:true}}); if(!company) throw new Error("Empresa ativa não encontrada.");
  const category=text(formData,"category"); const subject=text(formData,"subject"); const description=text(formData,"description"); if(!category||!subject||!description) throw new Error("Categoria, assunto e descrição são obrigatórios.");
  const protocol=`RH-${new Date().getFullYear()}-${Date.now().toString().slice(-8)}`;
  await prisma.hrTicket.create({data:{companyId:company.id,employeeId:text(formData,"employeeId"),protocol,category,subject,description,priority:text(formData,"priority")??"NORMAL"}});
  revalidatePath("/rh/canal-rh"); revalidatePath("/pessoas");
}
const statusLabel:Record<string,string>={OPEN:"Aberto",IN_PROGRESS:"Em atendimento",WAITING_EMPLOYEE:"Aguardando colaborador",RESOLVED:"Resolvido",CLOSED:"Encerrado"};
export default async function HrChannelPage(){
  const company=await prisma.company.findFirst({where:{active:true},select:{id:true}}); const companyId=company?.id;
  const [employees,tickets]=companyId?await Promise.all([
    prisma.hrEmployee.findMany({where:{companyId,active:true},orderBy:{fullName:"asc"},select:{id:true,fullName:true}}),
    prisma.hrTicket.findMany({where:{companyId},orderBy:{createdAt:"desc"},take:50,include:{employee:{select:{fullName:true}}}}),
  ]):[[],[]];
  const open=tickets.filter(i=>i.status==="OPEN"||i.status==="IN_PROGRESS").length; const waiting=tickets.filter(i=>i.status==="WAITING_EMPLOYEE").length;
  return <main className="px-4 py-6 md:px-7 md:py-8"><div className="mx-auto max-w-[1360px]"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#154b7a]">RH · Atendimento</p><h1 className="mt-2 text-3xl font-bold text-[#0b2947]">Canal RH</h1><p className="mt-2 text-sm text-slate-600">Atendimento humano, privado e rastreável ao colaborador, com protocolo e responsável.</p></div>
  <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Em atendimento",open],["Aguardando colaborador",waiting],["Resolvidos",tickets.filter(i=>i.status==="RESOLVED").length],["Protocolos",tickets.length]].map(([l,v])=><article key={String(l)} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs text-slate-500">{l}</p><strong className="mt-2 block text-2xl text-[#0b2947]">{String(v)}</strong></article>)}</section>
  <section className="mt-5 grid gap-5 xl:grid-cols-[420px_1fr]"><form action={createTicket} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#eaf3fb] text-[#154b7a]"><Plus className="h-5 w-5"/></div><div><h2 className="font-bold text-[#0b2947]">Abrir protocolo</h2><p className="text-xs text-slate-500">Atendimento realizado por pessoas do RH.</p></div></div><div className="mt-5 space-y-4"><select name="employeeId" className="h-11 w-full rounded-2xl border border-slate-200 px-3 text-sm"><option value="">Solicitação administrativa/sem vínculo</option>{employees.map(i=><option key={i.id} value={i.id}>{i.fullName}</option>)}</select><select name="category" required className="h-11 w-full rounded-2xl border border-slate-200 px-3 text-sm"><option value="">Categoria</option><option>Holerite e remuneração</option><option>Ponto e jornada</option><option>Benefícios</option><option>Férias</option><option>Documentos</option><option>Relações de trabalho</option><option>Outros</option></select><input name="subject" required placeholder="Assunto" className="h-11 w-full rounded-2xl border border-slate-200 px-4 text-sm"/><select name="priority" className="h-11 w-full rounded-2xl border border-slate-200 px-3 text-sm"><option value="NORMAL">Prioridade normal</option><option value="HIGH">Alta</option><option value="URGENT">Urgente</option></select><textarea name="description" required rows={5} placeholder="Descreva a solicitação" className="w-full rounded-2xl border border-slate-200 p-4 text-sm"/><button className="h-11 w-full rounded-2xl bg-[#0b2947] text-sm font-semibold text-white">Gerar protocolo</button></div></form>
  <article className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-6"><MessageSquareText className="h-5 w-5 text-[#154b7a]"/><div><h2 className="font-bold text-[#0b2947]">Fila de atendimento</h2><p className="text-xs text-slate-500">Protocolos mais recentes.</p></div></div>{tickets.length===0?<div className="p-12 text-center text-sm text-slate-500">Nenhum protocolo aberto.</div>:<div className="divide-y divide-slate-100">{tickets.map(item=><div key={item.id} className="grid gap-2 p-5 md:grid-cols-[150px_1.2fr_1fr_130px] md:items-center"><div><p className="font-semibold text-[#0b2947]">{item.protocol}</p><p className="text-xs text-slate-400">{item.category}</p></div><div><p className="font-semibold text-slate-800">{item.subject}</p><p className="text-xs text-slate-400">{item.employee?.fullName??"Administrativo"}</p></div><span className="text-sm text-slate-600">{new Intl.DateTimeFormat("pt-BR").format(item.createdAt)}</span><span className="w-fit rounded-full bg-blue-50 px-2.5 py-1 text-[11px] font-semibold text-blue-700">{statusLabel[item.status]??item.status}</span></div>)}</div>}</article></section>
  <div className="mt-5 flex gap-3 rounded-3xl border border-blue-100 bg-[#eef6fc] p-5 text-sm text-[#0b2947]"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0"/><p>Privacidade por padrão: o Canal RH é humano, restrito ao time autorizado e mantém histórico de atendimento para governança.</p></div>
  </div></main>;
}
